name: Run Tests
on:
  pull_request:

jobs:

  Build And Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./test/FsSCAD.Tests
      run: dotnet restore
    - name: Build projects
      working-directory: ./test/FsSCAD.Tests
      run: dotnet build --configuration Release --no-restore
    - name: Run tests
      working-directory: ./test/FsSCAD.Tests/bin/Release/net6.0
      run: dotnet test FsSCAD.Tests.dll
